language: python

python:
  - 3.7

install:
  - pip install -e .[dev]

script:
  # Style guide enforcement
  - flake8
  - yapf --quiet --recursive .
  # static typing
  - mypy .
  # Test suite
  - pytest